names(experiments)

# DONE
# player.q1_birthYear
# player.q2a_placeOfBirth_country
# player.q2b_placeOfBirth_state
# player.q2c_placeOfBirth_city
# player.q4_ethnicity
# player.q6a_sexGender
# player.q6b_sexGender_other
# player.q7_maritalStatus
# player.q8a_education_overview
# player.q8b_education_other            
# player.q8c_education_freshman        
# player.q8d_education_sophomore
# player.q8e_education_junior
# player.q8f_education_senior
# player.q8g_education_masters
# player.q8h_education_phD             
# player.q8i_education_eds
# player.q8j_education_edd
# player.q9_major
# player.q9_majorOther
# player.q10a_subject_econ             
# player.q10b_subject_finance
# player.q10c_subject_stat
# player.q11_military_service
# 
# DONE
# player.q12a_activities_academic
# player.q12b_activities_exercise      
# player.q12c_activities_sports
# player.q12d_activities_performing
# player.q12e_activites_religious
# player.q12f_activites_membership
# player.q12g_activities_leading       
# player.q12h_activities_socializing
# player.q12i_activities_socialNetworks
# player.q12j_activities_onlineGames
# player.q12l_activities_working
# 
# DONE
# player.trust_1
# player.trust_2
# player.trust_3 
# player.trust_4
# 
# DONE
# player.q13b_volunteer
# player.q13c_donations
# player.q13d_discussPolitics
# player.q13e_communicate
# player.q13f_demonstrate              
# player.q13g_elections
# player.q13h_risk 
# player.q14_l_networking_otherPrint
# 
# DONE
# player.q15a_ethics_wealth
# player.q15b_ethics_climate           
# player.q15c_ethics_gunControl
# 
# player.daringness   
# player.risky_project
# player.risky_project_outcome
# player.risky_project_2               
# player.risky_project_outcome_2
# 
# player.coinScenerio_1 
# player.coinScenerio_2
# player.coinScenerio_3 
# player.coinScenerio_4
# player.coinScenerio_5
# player.coinScenerio_6
# player.coinScenerio_7
# player.coinScenerio_8 
# player.coinScenerio_9                
# player.coinScenerio_10
# player.coinScenerio_11
# player.coinScenerio_12
# player.coinScenerio_13
# player.coinScenerio_14
# player.coinScenerio_15 
# player.coinScenerio_16
# player.coinScenerio_17
# player.coinScenerio_18
# player.coinScenerio_19               
# player.coinScenerio_20
# player.coinScenerio_21
# player.coinScenerio_22
# player.coinScenerio_23
# player.coinScenerio_24               
# player.coinScenerio_25
# player.coinScenerio_26
# player.coinScenerio_27
# player.coinScenerio_28
# player.coinScenerio_29               
# player.coinScenerio_30
# player.coinScenerio_31 
# 
# player.q14_1_prof_networkXFacebook   
# player.q14_2_prof_networkXTwitter
# player.q14_3_prof_networkXLinkedIn
# player.q14_4_prof_networkXInstagram
# player.q14_5_prof_networkXReddit
# player.q14_6_prof_networkXWhatsApp   
# player.q14_7_prof_networkXMeetup
# player.q14_8_prof_networkXNextdoor
# player.q14_9_prof_networkXSnapchat
# player.q14_10_prof_networkXWeibo
# player.q14_11_prof_networkXWeChat
# player.q14_12_soc_networkXFacebook
# player.q14_13_soc_networkXTwitter
# player.q14_14_soc_networkXLinkedIn
# player.q14_15_soc_networkXInstagram
# player.q14_16_soc_networkXReddit     
# player.q14_17_soc_networkXWhatsApp
# player.q14_18_soc_networkXMeetup
# player.q14_19_soc_networkXNextdoor
# player.q14_20_soc_networkXSnapchat
# player.q14_21_soc_networkXWeibo      
# player.q14_22_soc_networkXWeChat
# player.q14_23_xchng_infoXFacebook
# player.q14_24_xchng_infoXTwitter 
# player.q14_25_xchng_infoXLinkedIn
# player.q14_26_xchng_infoXInstagram
# player.q14_27_xchng_infoXReddit 
# player.q14_28_xchng_infoXWhatsApp 
# player.q14_29_xchng_infoXMeetup  
# player.q14_30_xchng_infoXNextdoor 
# player.q14_31_xchng_infoXSnapchat 
# player.q14_32_xchng_infoXWeibo  
# player.q14_33_xchng_infoXWeChat    
# player.q14_34_soc_eventsXFacebook  
# player.q14_35_soc_eventsXTwitter  
# player.q14_36_soc_eventsXLinkedIn 
# player.q14_37_soc_eventsXInstagram 
# player.q14_38_soc_eventsXReddit   
# player.q14_39_soc_eventsXWhatsApp 
# player.q14_40_soc_eventsXMeetup  
# player.q14_41_soc_eventsXNextdoor  
# player.q14_42_soc_eventsXSnapchat 
# player.q14_43_soc_eventsXWeibo    
# player.q14_44_soc_eventsXWeChat   
# player.q14_45_pol_eventsXFacebook  
# player.q14_46_pol_eventsXTwitter     
# player.q14_47_pol_eventsXLinkedIn  
# player.q14_48_pol_eventsXInstagram 
# player.q14_49_pol_eventsXReddit   
# player.q14_50_pol_eventsXWhatsApp  
# player.q14_51_pol_eventsXMeetup    
# player.q14_52_pol_eventsXNextdoor 
# player.q14_53_pol_eventsXSnapchat  
# player.q14_54_pol_eventsXWeibo     
# player.q14_55_pol_eventsXWeChat    
# player.q14_56_news_infoXFacebook   
# player.q14_57_news_infoXTwitter    
# player.q14_58_news_infoXLinkedIn   
# player.q14_59_news_infoXInstagram   
# player.q14_60_news_infoXReddit     
# player.q14_61_news_infoXWhatsApp     
# player.q14_62_news_infoXMeetup    
# player.q14_63_news_infoXNextdoor  
# player.q14_64_news_infoXSnapchat  
# player.q14_65_news_infoXWeibo     
# player.q14_66_news_infoXWeChat   
# player.q14_67_jobXFacebook        
# player.q14_68_jobXTwitter        
# player.q14_69_jobXLinkedIn       
# player.q14_70_jobXInstagram     
# player.q14_71_jobXReddit             
# player.q14_72_jobXWhatsApp   
# player.q14_73_jobXMeetup     
# player.q14_74_jobXNextdoor    
# player.q14_75_jobXSnapchat  
# player.q14_76_jobXWeibo    
# player.q14_77_jobXWeChat   
# player.q14_78_moneyXFacebook  
# player.q14_79_moneyXTwitter    
# player.q14_80_moneyXLinkedIn    
# player.q14_81_moneyXInstagram        
# player.q14_82_moneyXReddit     
# player.q14_83_moneyXWhatsApp  
# player.q14_84_moneyXMeetup   
# player.q14_85_moneyXNextdoor 
# player.q14_86_moneyXSnapchat         
# player.q14_87_moneyXWeibo     
# player.q14_88_moneyXWeChat     
# player.q14_89_gamesXFacebook    
# player.q14_90_gamesXTwitter    
# player.q14_91_gamesXLinkedIn         
# player.q14_92_gamesXInstagram  
# player.q14_93_gamesXReddit       
# player.q14_94_gamesXWhatsApp     
# player.q14_95_gamesXMeetup       
# player.q14_96_gamesXNextdoor         
# player.q14_97_gamesXSnapchat   
# player.q14_98_gamesXWeibo         
# player.q14_99_gamesXWeChat      
# player.q14_100_researchXFacebook 
# player.q14_101_researchXTwitter      
# player.q14_102_researchXLinkedIn  
# player.q14_103_researchXInstagram 
# player.q14_104_researchXReddit    
# player.q14_105_researchXWhatsApp  
# player.q14_106_researchXMeetup       
# player.q14_107_researchXNextdoor 
# player.q14_108_researchXSnapchat   
# player.q14_109_researchXWeibo     
# player.q14_110_researchXWeChat    
# player.q14_111_used_sitesXFacebook   
# player.q14_112_used_sitesXTwitter 
# player.q14_113_used_sitesXLinkedIn 
# player.q14_114_used_sitesXInstagram 
# player.q14_115_used_sitesXReddit  
# player.q14_116_used_sitesXWhatsApp   
# player.q14_117_used_sitesXMeetup  
# player.q14_118_used_sitesXNextdoor 
# player.q14_119_used_sitesXSnapchat 
# player.q14_120_used_sitesXWeibo   
# player.q14_121_used_sitesXWeChat